### ISSUE TITLE
'Input Data Source' change of structure in the viewed blueprint

### ISSUE THREAD

**Issue by valitsa** [valitsa/ESPmapping#24] opened 2013-10-04 12:35 UTC
The Input data source now is one column in the blueprint where users view info on the data source name and link if available. 
Make it two columns; one for the name and one for the link.

**Comment by brtvrbvk** [comment] 2013-10-07 12:49
so, one datasource per map? Or multiple? (currently one, schema allows for multiple datasources)

**Comment by valitsa** [comment] 2013-10-07 16:23
Multiple data sources per map

**Comment by willtemperley** [comment] 2013-10-15 11:44
Duplicate of:
https://github.com/valitsa/ESPmapping/issues/23

**Closed as completed** 2016-11-09 13:08 UTC
Labels: database
